services:
  - type: web
    name: jackpot-api
    env: docker
    region: ohio
    plan: free
    branch: feat/seeding-database
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
