spring.application.name=api

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/jackpotdb
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seed configuration
app.seed.enabled=true
