spring.application.name=api

# Server configuration
server.port=${PORT:8080}
# Database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/jackpotdb}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin123}

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Seed configuration
app.seed.enabled=true
